Repository Arkantik/miam, pull requests merged in 2023-04, with the labels that each got.

#3 RecipeCard component
  public/assets/icon/hat.svg
  public/assets/icon/hourglass.svg
  public/assets/icon/logged.svg
  public/assets/icon/search.svg
  public/assets/icon/user-group.svg
  src/App.jsx
  src/components/RecipeCard.jsx
  src/index.css
  tailwind.config.js
Labels: 🌟 enhancement

#5 Feat/login
  public/assets/icon/google.svg
  public/assets/icon/pass-hide.svg
  public/assets/icon/pass-show.svg
  src/App.css
  src/App.jsx
  src/components/Login.jsx
  src/components/RecipeCard.jsx
  src/index.css
  tailwind.config.js
Labels: 🌟 enhancement

#7 Feat/multi pages
  package-lock.json
  package.json
  src/App.jsx
  src/components/Navbar.jsx
  src/main.jsx
  src/routes/error-page.jsx
  src/routes/groceries.jsx
  src/routes/home.jsx
  src/routes/login.jsx
  src/routes/pantry.jsx
  src/routes/planner.jsx
  src/routes/recipes.jsx
  src/routes/register.jsx
Labels: 🌟 enhancement, ✅ Ready for merge

#9 Updated multi-pages
  src/components/Navbar.jsx
  src/index.css
  src/main.jsx
  src/pages/Groceries.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/NotFound.jsx
  src/pages/Pantry.jsx
  src/pages/Planner.jsx
  src/pages/Recipes.jsx
  src/pages/Register.jsx
Labels: 🌟 enhancement

#10 Added login and register pages
  src/components/Login.jsx
  src/components/LoginCard.jsx
  src/components/Register.jsx
  src/components/RegisterCard.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
  tailwind.config.js
Labels: 🌟 enhancement, ✅ Ready for merge

#11 Refactor/multi pages
  src/App.jsx
  src/components/LoginCard.jsx
  src/components/Navbar.jsx
  src/components/RecipeCard.jsx
  src/components/RegisterCard.jsx
  src/layouts/RootLayout.jsx
  src/main.jsx
  src/pages/Groceries.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/NotFound.jsx
  src/pages/Pantry.jsx
  src/pages/Planner.jsx
  src/pages/Recipes.jsx
  src/pages/Register.jsx
Labels: 🌟 enhancement

#12 Fixed console errors for the login and register pages, added blur to …
  src/components/LoginCard.jsx
  src/components/RegisterCard.jsx
  src/data/data.json
  src/pages/Login.jsx
Labels: 🌟 enhancement, 🔨 Bug fix

#13 Feat/search
  package-lock.json
  package.json
  src/components/Search.jsx
  src/pages/Recipes.jsx
  tailwind.config.js
Labels: 🌟 enhancement

#14 Hotfix/search
  public/assets/img/404.png
  src/components/Search.jsx
  src/layouts/RootLayout.jsx
  src/pages/NotFound.jsx
Labels: 🔨 Bug fix

#15 Feat/recipes data
  src/components/RecipeCard.jsx
  src/components/RecipesLibrary.jsx
  src/data/data-recipes.json
  src/data/data.json
  src/index.css
  src/layouts/RootLayout.jsx
  src/pages/Groceries.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/NotFound.jsx
  src/pages/Pantry.jsx
  src/pages/Planner.jsx
  src/pages/Recipes.jsx
  src/pages/Register.jsx
  tailwind.config.js
Labels: 🌟 enhancement, 🔨 Bug fix

#17 Hotfix/Login+Register
  src/components/LoginCard.jsx
  src/components/RegisterCard.jsx
Labels: 🌟 enhancement, 🔨 Bug fix

#18 Local fonts
  package-lock.json
  package.json
  public/assets/fonts/poppins-400-italic.ttf
  public/assets/fonts/poppins-400.ttf
  public/assets/fonts/poppins-500.ttf
  public/assets/fonts/poppins-600.ttf
  public/assets/fonts/poppins-700.ttf
  src/index.css
Labels: 🌟 enhancement

#19 hotfix/Search-bar
  src/components/Search.jsx
Labels: 🌟 enhancement, 🔨 Bug fix

#20 hotfix/Seach-bar
  src/components/Search.jsx
Labels: 🌟 enhancement

#28 feat/carousel
  package-lock.json
  package.json
  public/assets/icon/arrow-left.svg
  public/assets/icon/arrow-right.svg
  public/assets/img/tranding-food-1.png
  public/assets/img/tranding-food-2.png
  public/assets/img/tranding-food-3.png
  public/assets/img/tranding-food-4.png
  public/assets/img/tranding-food-5.png
  public/assets/img/tranding-food-6.png
  public/assets/img/tranding-food-7.png
  src/components/Carousel.jsx
  src/index.css
  src/pages/Home.jsx
Labels: ⚠️ Bug, 🌟 enhancement

#29 Added feature Add to Favorite when clicking on the card 'like' button
  package-lock.json
  package.json
  public/assets/icon/bookmark-light.svg
  public/assets/icon/bookmark.svg
  public/assets/icon/bookmarked.svg
  src/components/RecipeCard.jsx
  src/components/RecipesLibrary.jsx
  src/main.jsx
  src/pages/Recipes.jsx
Labels: 🌟 enhancement
